<Enter_intput@MDTextField>:
    hint_text: ""
    icon_right_color_normal: 1, 1, 1, .7
    icon_right_color_focus: 1, 1, 1, .7
    theme_text_color: "Custom"
    text_color: "black"
    mode: "round"
    bar_color: "gray"
    hint_text_color_normal: "gray"
    hint_text_color_focus: "white"
    text_color_focus: "black"
    text_color_normal: "black"
    line_color_focus: "blue"
    line_color_normal: 1, 1, 1, .5
    radius: [20, ]
    pos_hint: {"center_x": .5, "center_y": .5}
MDScreen:
    name: "add_depense"
    # prenom:prenom
    # nom:nom
    # list_data_:list_data_
    # add_picture:add_picture
    MDFloatLayout:
        # md_bg_color: "red"
        pos_hint: {"center_x": .5, "center_y": .5}

        MDLabel:
            text: "Nouvelle dépense"
            theme_text_color: "Custom"
            bold: True
            font_size: "25sp"
            text_color: "black"
            pos_hint: {"x": .1, "center_y": .95}
        MDIconButton:
            # id: mode_light_night
            icon: "close" # to go back
            pos_hint: {"center_x": .9, "center_y": .95}
            theme_text_color: "Custom"
            text_color: "black"
            md_bg_color: "gray"
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "gestion_des_vente_home"
        MDGridLayout:
            cols: 1
            rows: 8
            size_hint: .8, .5
            # padding: 10
            # md_bg_color: "red!"
            # spacing: 1
            pos_hint: {"x": .1, "top": .85}
            MDLabel:
                text: "Description *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                hint_text: ""
            
            MDLabel:
                text: "Montant (XOF) *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                hint_text: ""
            MDLabel:
                text: "Date *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                hint_text: ""
                helper_text: "exemple: 09/08/2026"
                helper_text_color_focus: "green"
            MDLabel:
                text: "Catégorie *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Categorie_choose:
                id: enter_categorie
        MDGridLayout:
            cols: 2
            rows: 1
            size_hint: .9, .1
            padding: 10
            spacing: 10
            pos_hint: {"center_x": .5, "center_y": .1}
            MDRectangleFlatButton:
                text: "Annuler"
                theme_text_color: "Custom"
                text_color:  "black"
                line_color: "gray"
                font_size: "20sp"
                size_hint: 1, 1
                on_release:
                    root.manager.transition.direction = "right"
                    root.manager.current = "gestion_des_vente_home"
            MDRectangleFlatButton:
                text: "Enregistrer"
                theme_text_color: "Custom"
                text_color: "white"
                bold: True
                line_color: 0, 0, 1, 0.8
                font_size: "20sp"
                size_hint: 1, 1
                md_bg_color: 0, 0, 1, 0.8
                on_release:
                    app.add_player(add_picture.image, prenom.text, nom.text, int(tir_bar.value/10), int(def_bar.value/10), int(pas_bar.value/10), int(dbl_bar.value/10))
<Categorie_choose@MDCard>:
    size_hint: .3, .5
    radius: [20, ]
    md_bg_color: 0, 0, 0, 0.5
    elevation: 4
    categorie_enter:categorie_enter
    MDFloatLayout:
        MDTextButton:
            text: categorie_enter.text
            pos_hint: {"center_x": .4, "center_y": .5}
            font_size: "15sp"
            theme_text_color: "Custom"
            text_color: "white"
        Spinner:
            id: categorie_enter
            text: "Achat de marchandise"
            radius: [20, ]
            values: ["Achat de marchandise","Transport/Livraison","Frais de personnel","Frais de communication","Frais de bureau","Autres"]
            opacity: 0
            pos_hint: {"center_x": .5, "center_y": .5}