MDScreen:
    name: "add_vente"
    date_achat:date_achat
    nom_client:nom_client
    numero_telephone:numero_telephone
    produit:produit
    montant:montant
    payement:payement
    MDFloatLayout:
        # md_bg_color: "red"
        pos_hint: {"center_x": .5, "center_y": .5}

        MDLabel:
            text: "Nouvelle Vente"
            theme_text_color: "Custom"
            bold: True
            font_size: "25sp"
            text_color: "black"
            pos_hint: {"x": .1, "center_y": .95}
        MDIconButton:
            # id: mode_light_night
            icon: "close" # to go back
            pos_hint: {"center_x": .9, "center_y": .95}
            theme_text_color: "Custom"
            text_color: "black"
            md_bg_color: "gray"
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "gestion_des_vente_home"
        MDGridLayout:
            cols: 2
            rows: 2
            size_hint: .8, .1
            # padding: 10
            # md_bg_color: "red"
            spacing: 10
            pos_hint: {"x": .1, "top": .32}
            MDLabel:
                text: "Date d'achat *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            MDLabel:
                text: "Statut *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            
            Enter_intput:
                id: date_achat
                hint_text: "05/08/2026"
                text: "05/08/2026"
                helper_text: "Exemple: 05/08/2026"
                helper_text_mode: "on_focus"
                helper_text_color_focus: "black"
            Categorie_choose_vente:
                id: payement
                
        MDGridLayout:
            # id: list_data_
            # tir_bar:tir_bar
            # pas_bar:pas_bar
            # def_bar:def_bar
            # dbl_bar:dbl_bar
            cols: 1
            rows: 8
            size_hint: .8, .5
            # padding: 10
            # md_bg_color: "red!"
            # spacing: 1
            pos_hint: {"x": .1, "top": .85}
            MDLabel:
                text: "Nom du client *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                id: nom_client
                hint_text: ""
            
            MDLabel:
                text: "Téléphone"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            
            Enter_intput:
                id: numero_telephone
                hint_text: ""
                # on_text:
            
            MDLabel:
                text: "Produit *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                id: produit
                hint_text: ""
            
            MDLabel:
                text: "Montant (XOF) *"
                theme_text_color: "Custom"
                halign: "left"
                font_size: "18sp"
                text_color: "black"
            Enter_intput:
                id: montant
                hint_text: ""
            
            
            
        MDGridLayout:
            cols: 2
            rows: 1
            size_hint: .9, .1
            padding: 10
            spacing: 10
            pos_hint: {"center_x": .5, "center_y": .1}
            MDRectangleFlatButton:
                text: "Annuler"
                theme_text_color: "Custom"
                text_color:  "black"
                line_color: "gray"
                font_size: "20sp"
                size_hint: 1, 1
                on_release:
                    root.manager.transition.direction = "right"
                    root.manager.current = "gestion_des_vente_home"
            MDRectangleFlatButton:
                text: "Enrégistrer"
                theme_text_color: "Custom"
                text_color: "white"
                bold: True
                line_color: 0, 0, 1, 0.8
                font_size: "20sp"
                size_hint: 1, 1
                md_bg_color: 0, 0, 1, 0.8
                on_release:
                    app.add_vente_detail(date_achat.text, nom_client.text, numero_telephone.text, produit.text, montant.text, payement.categorie.text)

<Categorie_choose_vente@MDCard>:
    size_hint: .3, .5
    radius: [20, ]
    md_bg_color: 0, 0, 0, 0.5
    elevation: 3
    categorie:categorie
    MDFloatLayout:
        MDTextButton:
            text: categorie.text
            pos_hint: {"center_x": .4, "center_y": .5}
            font_size: "15sp"
            theme_text_color: "Custom"
            text_color: "white"
        Spinner:
            id: categorie
            text:"Payé"
            radius: [20, ]
            values: ["Payé","Non payé"]
            opacity: 0
            pos_hint: {"center_x": .5, "center_y": .5}
<Enter_intput>:
    id: id_
    hint_text: ""
    on_text_validate: print(id_.text)
    icon_right_color_normal: 1, 1, 1, .7
    icon_right_color_focus: 1, 1, 1, .7
    theme_text_color: "Custom"
    text_color: "black"
    mode: "round"
    bar_color: "gray"
    hint_text_color_normal: "gray"
    hint_text_color_focus: "white"
    text_color_focus: "black"
    text_color_normal: "black"
    line_color_focus: "blue"
    line_color_normal: 1, 1, 1, .5
    radius: [20, ]
    pos_hint: {"center_x": .5, "center_y": .5}